import pytest
from unittest.mock import patch, mock_open, MagicMock
from fastapi import Request
from app.backend.services.copyparty_service import get_user_permissions_from_config, get_pmask
from pathlib import Path

def test_get_user_permissions_from_config_success():
    mock_conf = """# Generated by manage.py
--ah-alg sha2,424242
-a admin:pass
-a testuser:hash
-v /some/path:/:rwmda.,admin:r,testuser:rw,rwuser
"""
    with patch("builtins.open", mock_open(read_data=mock_conf)):
        assert get_user_permissions_from_config("admin") == "rwmda."
        assert get_user_permissions_from_config("testuser") == "r"
        assert get_user_permissions_from_config("rwuser") == "rw"

def test_get_user_permissions_from_config_grouped_users():
    mock_conf = "-v /some/path:/:r,user1,user2:rw,user3,user4\n"
    with patch("builtins.open", mock_open(read_data=mock_conf)):
        assert get_user_permissions_from_config("user1") == "r"
        assert get_user_permissions_from_config("user2") == "r"
        assert get_user_permissions_from_config("user3") == "rw"
        assert get_user_permissions_from_config("user4") == "rw"

def test_get_user_permissions_from_config_not_found():
    mock_conf = "-v /some/path:/:r,testuser\n"
    with patch("builtins.open", mock_open(read_data=mock_conf)):
        assert get_user_permissions_from_config("nonexistent") == ""

def test_get_user_permissions_from_config_file_missing():
    with patch("builtins.open", side_effect=FileNotFoundError):
        assert get_user_permissions_from_config("admin") == ""

def test_get_pmask_fallback_to_session():
    # Mock Request and Session
    request = MagicMock(spec=Request)
    session = MagicMock()
    session.permissions = "rwm"
    request.state.session = session
    
    # Mock requests.get to fail
    with patch("requests.get", side_effect=Exception("Backend down")):
        assert get_pmask(request, Path("some/dir")) == "rwm"

def test_get_pmask_no_session_fallback():
    # Mock Request with no session
    request = MagicMock(spec=Request)
    request.state.session = None
    
    # Mock requests.get to fail
    with patch("requests.get", side_effect=Exception("Backend down")):
        assert get_pmask(request, Path("some/dir")) == "r"

