import logging
from app.backend.database.session import SessionLocal
from app.backend.database.models import User
from .config import settings

logger = logging.getLogger(__name__)

def sync_users_to_copyparty():
    """
    Reads all active users from the SQLite database and writes a 
    Copyparty configuration file (copyparty.conf) as a list of CLI arguments.
    """
    db = SessionLocal()
    try:
        users = db.query(User).filter(User.is_active == True).all()
        
        user_entries = []
        for user in users:
            # For debugging, we'll try to find the plain text password if possible,
            # but since we only have hashes in DB, we'll use a known test password 
            # for the admin if we are in this debug phase.
            # OR, we just use the hash and ensure the prefix is correct.
            # ACTUALLY, let's keep the hash but ensure the formatting is perfect.
            if user.cp_hash:
                user_entries.append({
                    "username": user.username,
                    "hash": user.cp_hash,
                    "perms": user.permissions
                })
        
        write_config_file(user_entries)
    except Exception as e:
        logger.error(f"Failed to sync users to copyparty: {e}")
    finally:
        db.close()

def write_config_file(user_entries: list):
    """
    Writes the copyparty.conf file using the 'one argument per line' format.
    """
    conf_file = settings.BASE_DIR / "copyparty" / "copyparty.conf"
    conf_file.parent.mkdir(parents=True, exist_ok=True)
    
    lines = []
    lines.append("# Generated by FastAPI user_sync.py")
    lines.append("# Format: one CLI argument per line")
    lines.append("")

    # 1. Add Accounts
    for entry in user_entries:
        lines.append(f"-a {entry['username']}:{entry['hash']}")
    
    # 2. Define Root Volume (-v src:dst:perms)
    serve_path = str(settings.SERVE_PATH.resolve())
    
    # Construct the volume permission string
    # Start with the volume definition
    vol_arg = f"{serve_path}:/"
    
    # Map permission strings to lists of users
    perms_map = {}
    for entry in user_entries:
        p = entry['perms'] or 'r'
        # Normalize common admin strings to rwmda. (full access)
        if p.lower() in ('admin', 'rwma', 'rwmda.', 'a', 'A'):
            p = 'rwmda.'
        
        if p not in perms_map:
            perms_map[p] = []
        perms_map[p].append(entry['username'])

    # Append permissions to the volume argument
    for perm, users in perms_map.items():
        user_list = ",".join(users)
        vol_arg += f":{perm},{user_list}"
    
    lines.append(f"-v {vol_arg}")
        
    with open(conf_file, "w") as f:
        f.write("\n".join(lines) + "\n")
    
    logger.info(f"Successfully synced {len(user_entries)} users to {conf_file}")

if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    sync_users_to_copyparty()